remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on
gem "github-pages", group: :jekyll_plugins
title: Reza's Portfolio
description: A brief overview of my projects
